/* Country and dish data for African Flavors */
const countries = [
{ id: 'cote-divoire', name: 'Ivory Coast', flag: '🇨🇮' },
{ id: 'nigeria', name: 'Nigeria', flag: '🇳🇬' },
{ id: 'ghana', name: 'Ghana', flag: '🇬🇭' },
{ id: 'senegal', name: 'Senegal', flag: '🇸🇳' },
{ id: 'cameroun', name: 'Cameroon', flag: '🇨🇲' },
{ id: 'mali', name: 'Mali', flag: '🇲🇱' },
{ id: 'maroc', name: 'Morocco', flag: '🇲🇦' },
{ id: 'kenya', name: 'Kenya', flag: '🇰🇪' },
{ id: 'ethiopie', name: 'Ethiopia', flag: '🇪🇹' },
{ id: 'afrique-du-sud', name: 'South Africa', flag: '🇿🇦' }
];

const dishes = [
{
    id: 1,
    name: 'Alloco et oeuf',
    country: 'Ivory Coast',
    origin: 'Southern Ivory Coast',
    category: 'Street food',
    history: 'A popular street food where fried plantains are served with a palm nut-based sauce.',
    description: 'Golden fried plantains accompanied by a sauce made of palm nuts, tomatoes, and spices.',
    ingredients: ['Ripe plantains', 'Palm nuts', 'Tomato', 'Onion', 'Chili', 'Garlic'],
    flavors: ['Sweet', 'Salty', 'Nutty', 'Spicy'],
    spiceLevel: 2,
    prepTime: '35 min',
    priceXOF: 2200,
    priceUSD: 3.8,
    priceEUR: 3.5,
    drinkPairing: 'Fresh Hibiscus juice (Bissap)',
    image: '../images/alloco.jpg',
    funFact: 'The word "alloco" is often used to refer to fried plantains in Ivory Coast.'
},
{
    id: 2,
    name: 'Garba',
    country: 'Ivory Coast',
    origin: 'Abidjan',
    category: 'Popular dish',
    history: 'A fried fish dish topped with cassava semolina and a spicy sauce.',
    description: 'Fried tuna fillet served with cassava couscous, onions, and spicy broth.',
    ingredients: ['Tuna', 'Cassava couscous', 'Tomato', 'Chili', 'Lemon', 'Onion'],
    flavors: ['Umami', 'Sour', 'Spicy'],
    spiceLevel: 3,
    prepTime: '25 min',
    priceXOF: 2800,
    priceUSD: 4.8,
    priceEUR: 4.2,
    drinkPairing: 'Ginger juice',
    image: '../images/garba.jpg',
    funFact: 'Garba is one of the fastest street dishes to prepare in Abidjan.'
},
{
    id: 3,
    name: 'Foutou et Sauce Graine',
    country: 'Ivory Coast',
    origin: 'Lagoon region',
    category: 'Family dish',
    history: 'A traditional dish served at festivals and weddings with a rich nutty sauce.',
    description: 'Plantain or yam paste accompanied by a rich sauce made from ground palm seeds.',
    ingredients: ['Plantain', 'Palm nuts', 'Tomato', 'Onion', 'Smoked fish', 'Chili'],
    flavors: ['Rich', 'Nutty', 'Spicy'],
    spiceLevel: 3,
    prepTime: '50 min',
    priceXOF: 3200,
    priceUSD: 5.5,
    priceEUR: 4.8,
    drinkPairing: 'Iced Hibiscus juice (Bissap)',
    image: '../images/foutou-banane-avec-sauce-graine.jpg',
    funFact: 'Foutou is often hand-pounded to obtain its characteristic soft texture.'
},
{
    id: 4,
    name: 'Kedjénou',
    country: 'Ivory Coast',
    origin: 'Sud-Est',
    category: 'Seafood',
    history: 'A coastal dish originating from the region famous for its slightly fermented cassava semolina.',
    description: 'Cassava semolina served with grilled shrimp, salad, and chili.',
    ingredients: ['Attiéké', 'Shrimp', 'Onion', 'Tomato', 'Lemon', 'Chili'],
    flavors: ['Sour', 'Salty', 'Spicy'],
    spiceLevel: 3,
    prepTime: '30 min',
    priceXOF: 3500,
    priceUSD: 6.0,
    priceEUR: 5.2,
    drinkPairing: 'Tamarind juice',
    image: '../images/kedjénou.jpg',
    funFact: 'Attiéké is often compared to a cassava-based couscous.'
},
{
    id: 5,
    name: 'Bawin with riz',
    country: 'Ivory Coast',
    origin: 'Street food',
    category: 'Meat',
    history: 'Chicken marinated in local spices and then grilled over charcoal embers.',
    description: 'Juicy chicken pieces served with a spicy sauce and grilled vegetables.',
    ingredients: ['Chicken', 'Garlic', 'Ginger', 'Chili', 'Pepper', 'Coriander'],
    flavors: ['Smoked', 'Spicy', 'Aromatic'],
    spiceLevel: 4,
    prepTime: '45 min',
    priceXOF: 3700,
    priceUSD: 6.3,
    priceEUR: 5.5,
    drinkPairing: 'Fresh Hibiscus juice (Bissap)',
    image: '../images/bawin-riz.jpg',
    funFact: 'Braised chicken is a staple at Ivorian markets and festivals.'
  },
  {
    id: 6,
    name: 'Ivory cost ogro soup with snow',
    country: 'Ivory Coast',
    origin: 'Central Region',
    category: 'Ogro-soup',
    history: 'A traditional green dish prepared with local leaves and boiled meat.',
    description: 'Green leaves simmered with meat, palm oil, and spices, served with rice or foutou.',
    ingredients: ['Local leaves', 'Meat', 'Tomato', 'Onion', 'Palm oil', 'Chili'],
    flavors: ['Herbaceous', 'Rich', 'Lightly spiced'],
    spiceLevel: 2,
    prepTime: '40 min',
    priceXOF: 3000,
    priceUSD: 5.0,
    priceEUR: 4.4,
    drinkPairing: 'Ginger juice',
    image: '../images/sauce-ombo-aux-escargots.jpg',
    funFact: 'This dish highlights local leaves grown in village gardens.'
  },
  {
    id: 7,
    name: 'Jollof Rice',
    country: 'Nigeria',
    origin: 'West Africa',
    category: 'National dish',
    history: 'An iconic West African dish, often prepared for celebrations and weddings.',
    description: 'Fragrant red rice flavored with tomato broth, pepper, curry, and crunchy vegetables.',
    ingredients: ['Rice', 'Tomato', 'Bell pepper', 'Onion', 'Chili', 'Broth'],
    flavors: ['Tomatoey', 'Spicy', 'Aromatic'],
    spiceLevel: 3,
    prepTime: '50 min',
    priceXOF: 2600,
    priceUSD: 4.5,
    priceEUR: 3.9,
    drinkPairing: 'Hibiscus juice',
    image: '../images/jollof-rice.jpg',
    funFact: 'Jollof is at the center of many friendly culinary debates between West African countries.'
  },
  {
    id: 8,
    name: 'Egusi Soup',
    country: 'Nigeria',
    origin: 'Igbo Region',
    category: 'Soup',
    history: 'A soup made with dried and ground melon seeds, popular throughout the country.',
    description: 'A rich soup with spices, vegetables, and meat served with fufu or rice.',
    ingredients: ['Egusi', 'Spinach', 'Smoked fish', 'Onion', 'Chili', 'Palm oil'],
    flavors: ['Nutty', 'Spicy', 'Savory'],
    spiceLevel: 4,
    prepTime: '55 min',
    priceXOF: 2800,
    priceUSD: 4.9,
    priceEUR: 4.3,
    drinkPairing: 'Light beer',
    image: '../images/egusi-soup.jpg',
    funFact: 'Egusi means melon seeds in Yoruba and forms the base of the soup.'
  },
  {
    id: 9,
    name: 'Amala et Ewedu',
    country: 'Nigeria',
    origin: 'Western Nigeria',
    category: 'Side dish',
    history: 'A traditional Yoruba dish often served with a light ewedu leaf soup.',
    description: 'Yam paste served with a leaf soup and a spicy sauce.',
    ingredients: ['Yam flour', 'Ewedu', 'Tomato', 'Chili', 'Onion'],
    flavors: ['Earthy', 'Spicy', 'Light'],
    spiceLevel: 3,
    prepTime: '40 min',
    priceXOF: 2400,
    priceUSD: 4.2,
    priceEUR: 3.7,
    drinkPairing: 'Lemon water',
    image: '../images/amala-soupe-ewedu.jpg',
    funFact: 'Amala is particularly appreciated for its unique elastic texture.'
  },
  {
    id: 10,
    name: 'Moyin-moyin',
    country: 'Nigeria',
    origin: 'Southern Nigeria',
    category: 'Side dish',
    history: 'A dish made from ground beans, wrapped and steamed.',
    description: 'A savory spiced bean cake, sometimes garnished with eggs, fish, or meat.',
    ingredients: ['Beans', 'Bell pepper', 'Onion', 'Chili', 'Oil', 'Egg'],
    flavors: ['Light', 'Spicy', 'Savory'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 1800,
    priceUSD: 3.2,
    priceEUR: 2.8,
    drinkPairing: 'Cold tea',
    image: '../images/moyin-moyin.jpg',
    funFact: 'Moi-Moi can be served as a snack or a light main course.'
  },
  {
    id: 11,
    name: 'Suya',
    country: 'Nigeria',
    origin: 'Northern Nigeria',
    category: 'Skewer',
    history: 'Spicy grilled meat skewers, a popular evening street food.',
    description: 'Grilled beef marinated in peanuts and spices, served with raw onion.',
    ingredients: ['Beef', 'Peanut', 'Chili', 'Paprika', 'Cumin', 'Oil'],
    flavors: ['Spicy', 'Nutty', 'Smoked'],
    spiceLevel: 4,
    prepTime: '45 min',
    priceXOF: 3000,
    priceUSD: 5.0,
    priceEUR: 4.4,
    drinkPairing: 'Cold beer',
    image: '../images/le-suya.jpg',
    funFact: 'Suya is often sold with thin slices of onion and tomatoes.'
  },
  {
    id: 12,
    name: 'Végétable soup',
    country: 'Nigeria',
    origin: 'Igbo People',
    category: 'Soup',
    history: 'A rich side dish served with a soup made from ogbono seeds.',
    description: 'Smooth yam paste accompanied by a thick, flavorful soup.',
    ingredients: ['Yams', 'Ogbono', 'Spinach', 'Smoked fish', 'Chili'],
    flavors: ['Rich', 'Spicy', 'Creamy'],
    spiceLevel: 3,
    prepTime: '50 min',
    priceXOF: 2900,
    priceUSD: 4.9,
    priceEUR: 4.3,
    drinkPairing: 'Natural water',
    image: '../images/vegetable-soup.jpg',
    funFact: 'Ogbono seeds give the soup its characteristic slippery texture.'
  },
  {
    id: 13,
    name: 'Banku et Tilapia',
    country: 'Ghana',
    origin: 'Coastal Zone',
    category: 'Fish',
    history: 'Banku is a fermented dough served with grilled fish and a spicy sauce.',
    description: 'Corn and cassava dough, accompanied by grilled tilapia and chili sauce.',
    ingredients: ['Corn', 'Cassava', 'Tilapia', 'Tomato', 'Onion', 'Chili'],
    flavors: ['Sour', 'Spicy', 'Smoked'],
    spiceLevel: 3,
    prepTime: '45 min',
    priceXOF: 3200,
    priceUSD: 5.3,
    priceEUR: 4.6,
    drinkPairing: 'Ginger beer',
    image: '../images/banku-and-tilapia-ghana.jpg',
    funFact: 'Banku is often eaten with the hands to better appreciate its texture.'
  },
  {
    id: 14,
    name: 'Red Red',
    country: 'Ghana',
    origin: 'Western Region',
    category: 'Vegetarian',
    history: 'A simple dish made from red beans and fried plantains.',
    description: 'Beans simmered in a spicy tomato sauce, served with golden plantains.',
    ingredients: ['Red beans', 'Tomato', 'Plantains', 'Onion', 'Chili', 'Palm oil'],
    flavors: ['Sweet', 'Spicy', 'Rich'],
    spiceLevel: 2,
    prepTime: '40 min',
    priceXOF: 2500,
    priceUSD: 4.1,
    priceEUR: 3.6,
    drinkPairing: 'Hibiscus juice',
    image: '../images/red-red-ghana.jpg',
    funFact: 'Red Red is often eaten during fasting days or as a family meal.'
  },
  {
    id: 15,
    name: 'Waakye',
    country: 'Ghana',
    origin: 'Northern Ghana',
    category: 'Main course',
    history: 'A traditional street food consisting of rice and beans cooked together with local leaves.',
    description: 'Rice and beans served with gari, boiled eggs, spaghetti, and spicy sauce.',
    ingredients: ['Rice', 'Beans', 'Gari', 'Egg', 'Spaghetti', 'Chili'],
    flavors: ['Savory', 'Spicy', 'Hearty'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 2700,
    priceUSD: 4.5,
    priceEUR: 3.9,
    drinkPairing: 'Coconut juice',
    image: '../images/ghanna-waakye.jpg',
    funFact: 'Waakye is considered a popular breakfast specialty in Ghana.'
  },
  {
    id: 16,
    name: 'Kenkey and Fried Fish',
    country: 'Ghana',
    origin: 'Ghanaian Coast',
    category: 'Side dish',
    history: 'Kenkey is a fermented dough wrapped in leaves and served with fried fish.',
    description: 'Fermented corn dough, crispy fried fish, and chili sauce.',
    ingredients: ['Corn', 'Fish', 'Chili', 'Onion', 'Salt'],
    flavors: ['Sour', 'Crunchy', 'Spicy'],
    spiceLevel: 3,
    prepTime: '1 h 15 min',
    priceXOF: 3100,
    priceUSD: 5.1,
    priceEUR: 4.5,
    drinkPairing: 'Ginger beer',
    image: '../images/kenkey-and-fried-fish-ghana.jpg',
    funFact: 'The fermentation process gives kenkey its characteristic tangy taste.'
  },
  {
    id: 17,
    name: 'Fufu and Soup',
    country: 'Ghana',
    origin: 'Southern Ghana',
    category: 'Side dish',
    history: 'A classic dish consisting of a dough and a rich soup, popular in many families.',
    description: 'Cassava or yam dough accompanied by a vegetable and meat soup.',
    ingredients: ['Cassava', 'Yam', 'Smoked fish', 'Onion', 'Chili', 'Spinach'],
    flavors: ['Comforting', 'Herbaceous', 'Spicy'],
    spiceLevel: 2,
    prepTime: '55 min',
    priceXOF: 2800,
    priceUSD: 4.8,
    priceEUR: 4.2,
    drinkPairing: 'Mint-flavored water',
    image: '../images/fufu-and-soup-ghana.jpg',
    funFact: 'Fufu is loved for its soft texture and its ability to absorb sauces.'
  },
  {
    id: 18,
    name: 'Red Red Deluxe',
    country: 'Ghana',
    origin: 'Street Food',
    category: 'Vegetarian',
    history: 'A richer variant of Red Red, often served with an egg and smoked fish.',
    description: 'Spiced red beans, fried plantains, and a poached egg on top.',
    ingredients: ['Red beans', 'Plantains', 'Egg', 'Tomato', 'Spices', 'Oil'],
    flavors: ['Sweet', 'Spicy', 'Rich'],
    spiceLevel: 3,
    prepTime: '45 min',
    priceXOF: 2900,
    priceUSD: 4.9,
    priceEUR: 4.3,
    drinkPairing: 'Tiger milk',
    image: '../images/le-suya.jpg',
    funFact: 'Red Red is a dish often associated with the street songs of Ghana.'
  },
  {
    id: 19,
    name: 'Thiéboudienne',
    country: 'Senegal',
    origin: 'Senegalese Cuisine',
    category: 'National dish',
    history: 'The national dish of Senegal, made with fish, rice, and vegetables in a fragrant broth.',
    description: 'Rice cooked in fish broth and vegetables, served with a spicy tomato sauce.',
    ingredients: ['Rice', 'Fish', 'Tomato', 'Cabbage', 'Carrot', 'Chili'],
    flavors: ['Tomatoey', 'Umami', 'Spicy'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 3000,
    priceUSD: 5.0,
    priceEUR: 4.4,
    drinkPairing: 'Hibiscus juice',
    image: '../images/thiéboudienne-senegal.jpg',
    funFact: 'Thiéboudienne means "rice with fish" in Wolof.'
  },
  {
    id: 20,
    name: 'Poulet Yassa',
    country: 'Senegal',
    origin: 'Festive Events',
    category: 'Meat',
    history: 'A dish of chicken marinated in onions and lemon, popular throughout West Africa.',
    description: 'Chicken marinated in lemon and caramelized onions, served with white rice.',
    ingredients: ['Chicken', 'Lemon', 'Onion', 'Mustard', 'Chili', 'Garlic'],
    flavors: ['Sour', 'Caramelized', 'Spicy'],
    spiceLevel: 2,
    prepTime: '1 h 10 min',
    priceXOF: 3200,
    priceUSD: 5.3,
    priceEUR: 4.6,
    drinkPairing: 'Mint tea',
    image: '../images/poulet-yassa-senegal.jpg',
    funFact: 'Yassa likely has its origins among the Wolof people of Senegal.'
  },
  {
    id: 21,
    name: 'Mafé',
    country: 'Senegal',
    origin: 'Timbuktu Region',
    category: 'Stew',
    history: 'A creamy peanut sauce stew, very popular in Senegal and Mali.',
    description: 'Meat or fish simmered in a smooth peanut paste sauce.',
    ingredients: ['Beef', 'Peanut paste', 'Tomato', 'Carrot', 'Onion', 'Chili'],
    flavors: ['Nutty', 'Rich', 'Salty'],
    spiceLevel: 2,
    prepTime: '1 h 15 min',
    priceXOF: 3300,
    priceUSD: 5.5,
    priceEUR: 4.8,
    drinkPairing: 'Iced tea',
    image: '../images/mafé-senegal.jpg',
    funFact: 'Mafé is sometimes simply called "peanut sauce" in West African cuisine.'
  },
  {
    id: 22,
    name: 'Pastels',
    country: 'Senegal',
    origin: 'Street food',
    category: 'Snack',
    history: 'Fried pastries stuffed with spiced fish, highly popular as a street snack.',
    description: 'Crispy pockets filled with fish, onions, and spices.',
    ingredients: ['Flour', 'Fish', 'Onion', 'Chili', 'Oil', 'Salt'],
    flavors: ['Crispy', 'Spicy', 'Savory'],
    spiceLevel: 3,
    prepTime: '45 min',
    priceXOF: 2100,
    priceUSD: 3.5,
    priceEUR: 3.0,
    drinkPairing: 'Hibiscus juice',
    image: '../images/les-pastels-senegal.jpg',
    funFact: 'Pastels are often served with a homemade spicy sauce.'
  },
  {
    id: 23,
    name: 'Dibi',
    country: 'Senegal',
    origin: 'Street food',
    category: 'Grill',
    history: 'Aromatized grilled lamb, often served in bread or with rice.',
    description: 'Grilled pieces of lamb, presented with onions, spices, and flatbread.',
    ingredients: ['Lamb', 'Onion', 'Cumin', 'Chili', 'Lemon', 'Oil'],
    flavors: ['Smoked', 'Spicy', 'Aromatic'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 3400,
    priceUSD: 5.6,
    priceEUR: 4.9,
    drinkPairing: 'Ginger juice',
    image: '../images/dibi-senegal.jpg',
    funFact: 'Dibi means "grilled" in the Wolof language.'
  },
  {
    id: 24,
    name: 'Soupou Kandja',
    country: 'Senegal',
    origin: 'Southern Cuisine',
    category: 'Stew',
    history: 'A stew made from okra and meat, very typical of Senegalese families.',
    description: 'Okra simmered with fish, meat, and aromatic herbs.',
    ingredients: ['Okra', 'Fish', 'Onion', 'Tomato', 'Chili', 'Lemon'],
    flavors: ['Herbaceous', 'Spicy', 'Sour'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 3100,
    priceUSD: 5.1,
    priceEUR: 4.5,
    drinkPairing: 'Mint tea',
    image: '../images/soupou-kandja-senegal.jpg',
    funFact: 'Soupou Kandja is often served during Sunday family meals.'
  },
  {
    id: 25,
    name: 'Ndolé',
    country: 'Cameroon',
    origin: 'Littoral Region',
    category: 'Vegetables',
    history: 'The national dish of Cameroon made from bitter leaves and peanut paste.',
    description: 'Bitter leaves simmered with meat, shrimp, and peanut sauce.',
    ingredients: ['Ndolé leaves', 'Peanut paste', 'Meat', 'Shrimp', 'Onion', 'Chili'],
    flavors: ['Bitter', 'Nutty', 'Rich'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 3400,
    priceUSD: 5.6,
    priceEUR: 4.9,
    drinkPairing: 'Hibiscus juice',
    image: '../images/ndolé-cameroun.jpg',
    funFact: 'Ndolé is a center-piece at Cameroonian ceremonies and family events.'
  },
  {
    id: 26,
    name: 'Pork Condre',
    country: 'Cameroon',
    origin: 'Urban Regional Cuisine',
    category: 'Meat',
    history: 'A spicy pork stew, easy to share with plantains or rice.',
    description: 'Pork shoulder simmered with tomatoes, onions, and hot chili.',
    ingredients: ['Pork', 'Tomato', 'Chili', 'Onion', 'Garlic', 'Oil'],
    flavors: ['Spicy', 'Salty', 'Rich'],
    spiceLevel: 4,
    prepTime: '1 h 10 min',
    priceXOF: 3600,
    priceUSD: 5.8,
    priceEUR: 5.1,
    drinkPairing: 'Ginger juice',
    image: '../images/condré-de-por-cameroun.jpg',
    funFact: 'Condre is a specialty often prepared for neighborhood block parties.'
  },
  {
    id: 27,
    name: 'Koki',
    country: 'Cameroon',
    origin: 'Central Cameroon',
    category: 'Side dish',
    history: 'A macabo pea pudding steamed and wrapped in banana leaves.',
    description: 'A jellied preparation of split peas, often served with bobolo.',
    ingredients: ['Macabo peas', 'Banana leaves', 'Palm oil', 'Salt', 'Chili'],
    flavors: ['Light', 'Herbaceous', 'Nutty'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 2600,
    priceUSD: 4.3,
    priceEUR: 3.8,
    drinkPairing: 'Flavored water',
    image: '../images/koki-cameroun.jpg',
    funFact: 'Koki is often prepared to accompany traditional festive meals.'
  },
  {
    id: 28,
    name: 'Poulet DG',
    country: 'Cameroon',
    origin: 'Douala',
    category: 'Meat',
    history: 'A festive dish from the Cameroonian Littoral called "Director General" for its elegance.',
    description: 'Marinated chicken served with plantains and sautéed vegetables.',
    ingredients: ['Chicken', 'Plantains', 'Carrot', 'Cabbage', 'Onion', 'Garlic'],
    flavors: ['Sweet', 'Salty', 'Aromatic'],
    spiceLevel: 2,
    prepTime: '1 h 15 min',
    priceXOF: 3800,
    priceUSD: 6.2,
    priceEUR: 5.4,
    drinkPairing: 'Hibiscus juice',
    image: '../images/poulet-dg-cameroun.jpg',
    funFact: 'The name "DG" comes from the idea that it is worthy of a "Director General".'
  },
  {
    id: 29,
    name: 'Soya Street Food',
    country: 'Cameroon',
    origin: 'Street food',
    category: 'Grill',
    history: 'Spiced meat skewers sold on the streets by many local vendors.',
    description: 'Spiced grilled beef served with fresh onions and hot sauce.',
    ingredients: ['Beef', 'Chili', 'Peanut', 'Onion', 'Lemon', 'Spices'],
    flavors: ['Smoked', 'Spicy', 'Crispy'],
    spiceLevel: 4,
    prepTime: '45 min',
    priceXOF: 2800,
    priceUSD: 4.6,
    priceEUR: 4.0,
    drinkPairing: 'Light beer',
    image: '../images/soyaLe-street-food-cameroun.jpg',
    funFact: 'Soya is often accompanied by cassava sticks or fried plantains.'
  },
  {
    id: 30,
    name: 'Taro with Yellow Sauce',
    country: 'Cameroon',
    origin: 'Central Region',
    category: 'Side dish',
    history: 'Taro roots served with a spicy palm oil sauce.',
    description: 'Tender taro topped with a sauce rich in spices and local herbs.',
    ingredients: ['Taro', 'Palm oil', 'Tomato', 'Onion', 'Chili'],
    flavors: ['Rich', 'Spicy', 'Earthy'],
    spiceLevel: 3,
    prepTime: '50 min',
    priceXOF: 2700,
    priceUSD: 4.5,
    priceEUR: 3.9,
    drinkPairing: 'Lime juice',
    image: '../images/Taro-à-la-sauce-jaune-cameroun.jpg',
    funFact: 'Taro is appreciated for its soft and slightly starchy texture.'
  },
  {
    id: 31,
    name: 'Malian Fatty Rice',
    country: 'Mali',
    origin: 'Malian Cuisine',
    category: 'National dish',
    history: 'A traditional Malian dish served during Sunday family meals.',
    description: 'Rice cooked in a peanut broth with meat and fragrant vegetables.',
    ingredients: ['Rice', 'Beef rib', 'Carrot', 'Tomato', 'Peanut', 'Onion'],
    flavors: ['Rich', 'Nutty', 'Tomatoey'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 3100,
    priceUSD: 5.1,
    priceEUR: 4.5,
    drinkPairing: 'Hibiscus juice',
    image: '../images/riz-au-gras-malien.jpg',
    funFact: 'Riz au gras is often compared to Jollof rice but with an added peanut sauce touch.'
  },
  {
    id: 32,
    name: 'Tiguadégué',
    country: 'Mali',
    origin: 'Malian Cuisine',
    category: 'Stew',
    history: 'A meat stew in sauce often served with rice or millet paste (tô).',
    description: 'Meat simmered in a rich sauce accompanied by vegetables and spices.',
    ingredients: ['Meat', 'Tomato', 'Carrot', 'Onion', 'Chili', 'Peanut'],
    flavors: ['Rich', 'Savory', 'Spicy'],
    spiceLevel: 3,
    prepTime: '1 h',
    priceXOF: 3300,
    priceUSD: 5.5,
    priceEUR: 4.8,
    drinkPairing: 'Ginger juice',
    image: '../images/tiguadégué-mali.jpg',
    funFact: 'The name comes from the Bambara language and means "thick sauce".'
  },
  {
    id: 33,
    name: 'Djouka',
    country: 'Mali',
    origin: 'Southern Mali',
    category: 'Grain',
    history: 'A dish made from millet or rice served with an eucalyptus or peanut sauce.',
    description: 'Cooked grain accompanied by a fragrant sauce and meat or fish.',
    ingredients: ['Millet', 'Rice', 'Meat', 'Peanut', 'Onion', 'Chili'],
    flavors: ['Rich', 'Nutty', 'Salty'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 2900,
    priceUSD: 4.8,
    priceEUR: 4.2,
    drinkPairing: 'Lemon water',
    image: '../images/djouka-mali.jpg',
    funFact: 'Djouka is sometimes served during important family ceremonies.'
  },
  {
    id: 34,
    name: 'Fakoye',
    country: 'Mali',
    origin: 'Peul Cuisine',
    category: 'Sauce',
    history: 'A thick sauce often served with tô or rice, based on peanuts or leaves.',
    description: 'Rich sauce accompanying cereals, flavored with tomatoes and chili.',
    ingredients: ['Peanut', 'Tomato', 'Onion', 'Chili', 'Green leaves'],
    flavors: ['Nutty', 'Spicy', 'Rich'],
    spiceLevel: 3,
    prepTime: '45 min',
    priceXOF: 2600,
    priceUSD: 4.3,
    priceEUR: 3.8,
    drinkPairing: 'Black tea',
    image: '../images/fakoye-mali.jpg',
    funFact: 'Fakoye literally means "yellow sauce" in some regions.'
  },
  {
    id: 35,
    name: 'Widjila',
    country: 'Mali',
    origin: 'Kayes Region',
    category: 'Vegetables',
    history: 'A dish made with local leaves and meat or fish, often very fragrant.',
    description: 'Green leaves simmered with meat, peanut paste, and spices.',
    ingredients: ['Green leaves', 'Meat', 'Peanut', 'Tomato', 'Chili'],
    flavors: ['Herbaceous', 'Rich', 'Spicy'],
    spiceLevel: 3,
    prepTime: '50 min',
    priceXOF: 2800,
    priceUSD: 4.8,
    priceEUR: 4.2,
    drinkPairing: 'Coconut water',
    image: '../images/widjila-mali.jpg',
    funFact: 'Widjila is loved for its melting texture and strong aromas.'
  },
  {
    id: 36,
    name: 'Millet Couscous',
    country: 'Mali',
    origin: 'Northern Mali',
    category: 'Side dish',
    history: 'A couscous made from millet served with meat or vegetable sauces.',
    description: 'Millet semolina accompanied by a rich stew and local aromatics.',
    ingredients: ['Millet', 'Meat', 'Vegetables', 'Spices', 'Oil'],
    flavors: ['Nutty', 'Rich', 'Savory'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 3000,
    priceUSD: 5.0,
    priceEUR: 4.4,
    drinkPairing: 'Mint tea',
    image: '../images/couscous-de mil-mali.jpg',
    funFact: 'Millet is an ancestral grain widely used in Saharan Africa.'
  },
  {
    id: 37,
    name: 'Moroccan Couscous',
    country: 'Morocco',
    origin: 'Maghreb',
    category: 'National dish',
    history: 'An iconic dish of Morocco, often prepared for large family meals.',
    description: 'Wheat semolina flavored with spices, served with vegetables and tender meat.',
    ingredients: ['Semolina', 'Eggplant', 'Carrot', 'Chickpeas', 'Ras el hanout', 'Meat'],
    flavors: ['Aromatic', 'Mildly spicy', 'Herbaceous'],
    spiceLevel: 2,
    prepTime: '1 h 20 min',
    priceXOF: 3600,
    priceUSD: 5.7,
    priceEUR: 5.0,
    drinkPairing: 'Mint tea',
    image: '../images/couscous-maroc.jpg',
    funFact: 'Couscous is traditionally eaten on Fridays, the day of family reunions.'
  },
  {
    id: 38,
    name: 'Chicken Tajine',
    country: 'Morocco',
    origin: 'Berber Cuisine',
    category: 'Stew',
    history: 'A slow-cooked stew prepared in a conical clay dish called a tajine, with sweet-savory flavors.',
    description: 'Chicken simmered with olives, preserved lemon, and mild spices.',
    ingredients: ['Chicken', 'Preserved lemon', 'Olives', 'Ras el hanout', 'Onion', 'Coriander'],
    flavors: ['Sweet', 'Sour', 'Aromatic'],
    spiceLevel: 2,
    prepTime: '1 h 30 min',
    priceXOF: 3800,
    priceUSD: 6.0,
    priceEUR: 5.2,
    drinkPairing: 'Mint tea',
    image: '../images/tajine-maroc.jpg',
    funFact: 'The tajine takes its name from the earthenware cooking pot used for centuries.'
  },
  {
    id: 39,
    name: 'Chicken Pastilla',
    country: 'Morocco',
    origin: 'Fez Medina',
    category: 'Savory pastry',
    history: 'A sweet-and-savory festive pastry made with phyllo sheets, traditional at weddings.',
    description: 'A flaky pie stuffed with chicken, toasted almonds, and mild spices.',
    ingredients: ['Phyllo pastry', 'Chicken', 'Almonds', 'Cinnamon', 'Sugar', 'Onion'],
    flavors: ['Sweet', 'Mildly spicy', 'Nutty'],
    spiceLevel: 1,
    prepTime: '1 h 45 min',
    priceXOF: 4000,
    priceUSD: 6.5,
    priceEUR: 5.6,
    drinkPairing: 'Mint tea',
    image: '../images/pastilla-maroc.jpg',
    funFact: 'Pastilla combines Andalusian, Berber, and Arab influences.'
  },
  {
    id: 40,
    name: 'Rfissa',
    country: 'Morocco',
    origin: 'Traditional Cuisine',
    category: 'Festive dish',
    history: 'A festive dish served at births and major family gatherings.',
    description: 'Spiced chicken served on shreds of msemen flatbread soaked in broth.',
    ingredients: ['Msemen', 'Chicken', 'Lentils', 'Fenugreek', 'Cumin', 'Ras el hanout'],
    flavors: ['Aromatic', 'Mildly spicy', 'Herbaceous'],
    spiceLevel: 2,
    prepTime: '1 h 30 min',
    priceXOF: 3900,
    priceUSD: 6.2,
    priceEUR: 5.4,
    drinkPairing: 'Mint tea',
    image: '../images/rfissa-maroc.jpg',
    funFact: 'Rfissa is traditionally served to celebrate the birth of a child.'
  },
  {
    id: 41,
    name: 'Harira',
    country: 'Morocco',
    origin: 'Ramadan',
    category: 'Soup',
    history: 'A Moroccan soup consumed to break the fast, rich in legumes.',
    description: 'A thick soup based on lentils, chickpeas, meat, and tomatoes.',
    ingredients: ['Lentils', 'Chickpeas', 'Tomato', 'Meat', 'Coriander', 'Vermicelli'],
    flavors: ['Rich', 'Tomatoey', 'Aromatic'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 2800,
    priceUSD: 4.6,
    priceEUR: 4.0,
    drinkPairing: 'Mint tea',
    image: '../images/Harira-maroc.jpg',
    funFact: 'Harira holds a central place during Ramadan in Morocco.'
  },
  {
    id: 42,
    name: 'Bissara',
    country: 'Morocco',
    origin: 'Northern Morocco',
    category: 'Puree',
    history: 'Broad bean puree served with olive oil and spices, very popular at breakfast.',
    description: 'Creamy broad bean puree, seasoned with cumin and served with bread and oil.',
    ingredients: ['Broad beans', 'Garlic', 'Cumin', 'Olive oil', 'Lemon', 'Chili'],
    flavors: ['Nutty', 'Spicy', 'Creamy'],
    spiceLevel: 2,
    prepTime: '40 min',
    priceXOF: 2200,
    priceUSD: 3.8,
    priceEUR: 3.5,
    drinkPairing: 'Moroccan coffee',
    image: '../images/bissara-maroc.jpg',
    funFact: 'Bissara is often eaten in winter for its comforting qualities.'
  },
  {
    id: 43,
    name: 'Ugali et Sukuma Wiki',
    country: 'Kenya',
    origin: 'Kenyan Cuisine',
    category: 'Daily dish',
    history: 'A Kenyan staple, easy to prepare and consumed across the country.',
    description: 'Cornmeal paste served with a sauté of spiced collard greens and fresh tomatoes.',
    ingredients: ['Corn', 'Cabbage', 'Tomato', 'Onion', 'Garlic', 'Chili'],
    flavors: ['Earthy', 'Spicy', 'Herbaceous'],
    spiceLevel: 2,
    prepTime: '35 min',
    priceXOF: 2400,
    priceUSD: 4.1,
    priceEUR: 3.6,
    drinkPairing: 'Fresh water',
    image: '../images/ugali-kenya.jpg',
    funFact: 'Ugali is the most consumed dish in Kenya and Tanzania.'
  },
  {
    id: 44,
    name: 'Githeri',
    country: 'Kenya',
    origin: 'Kikuyu Cuisine',
    category: 'Vegetarian',
    history: 'A simple mix of corn and beans, often prepared in large quantities.',
    description: 'Beans and corn simmered with onions, tomatoes, and local spices.',
    ingredients: ['Corn', 'Beans', 'Tomato', 'Onion', 'Chili', 'Garlic'],
    flavors: ['Rich', 'Mildly spicy', 'Comforting'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 2600,
    priceUSD: 4.3,
    priceEUR: 3.8,
    drinkPairing: 'Black tea',
    image: '../images/githeri-kenya.jpg',
    funFact: 'Githeri is frequently served at school and community events.'
  },
  {
    id: 45,
    name: 'Irio',
    country: 'Kenya',
    origin: 'Kikuyu Cuisine',
    category: 'Side dish',
    history: 'A mash of potatoes, peas, and corn, very popular in central Kenya.',
    description: 'Colorful puree of potatoes, peas, and corn, often served with a stew.',
    ingredients: ['Potatoes', 'Peas', 'Corn', 'Butter', 'Salt'],
    flavors: ['Creamy', 'Light', 'Sweetness'],
    spiceLevel: 1,
    prepTime: '35 min',
    priceXOF: 2200,
    priceUSD: 3.8,
    priceEUR: 3.5,
    drinkPairing: 'Lemon juice',
    image: '../images/irio-ou-mukimo-kenya.jpg',
    funFact: 'Irio is often served during traditional Kikuyu celebrations.'
  },
  {
    id: 46,
    name: 'Nyama Choma',
    country: 'Kenya',
    origin: 'Kenyan Cuisine',
    category: 'Grill',
    history: 'Barbecued meat, very popular during outdoor social gatherings.',
    description: 'Juicy grilled meat served with a side of tomatoes and onions.',
    ingredients: ['Meat', 'Salt', 'Pepper', 'Garlic', 'Onion', 'Lemon'],
    flavors: ['Smoked', 'Salty', 'Juicy'],
    spiceLevel: 2,
    prepTime: '50 min',
    priceXOF: 3600,
    priceUSD: 5.7,
    priceEUR: 5.0,
    drinkPairing: 'Local beer',
    image: '../images/nyama-homa-kenya.jpg',
    funFact: 'Nyama Choma is usually accompanied by kachumbari, a fresh tomato and onion salad.'
  },
  {
    id: 47,
    name: 'Pilau',
    country: 'Kenya',
    origin: 'Coastal Cuisine',
    category: 'Spiced rice',
    history: 'Fragrant spiced rice served at celebrations such as weddings.',
    description: 'Rice cooked with meat, whole spices, and vegetables, rich in aromas.',
    ingredients: ['Rice', 'Meat', 'Cinnamon', 'Cloves', 'Onion', 'Chili'],
    flavors: ['Aromatic', 'Spicy', 'Rich'],
    spiceLevel: 3,
    prepTime: '1 h 20 min',
    priceXOF: 3400,
    priceUSD: 5.3,
    priceEUR: 4.6,
    drinkPairing: 'Chai tea',
    image: '../images/pilau-kenyan-kenya.jpg',
    funFact: 'Kenyan pilau has its roots in the trade history of the Swahili coast.'
  },
  {
    id: 48,
    name: 'Sukuma Wiki',
    country: 'Kenya',
    origin: 'Everyday Cuisine',
    category: 'Vegetables',
    history: 'A sautéed kale dish served as a side in many Kenyan households.',
    description: 'Green kale sautéed with tomatoes, onions, and spices, simple and nourishing.',
    ingredients: ['Kale', 'Tomato', 'Onion', 'Garlic', 'Chili', 'Oil'],
    flavors: ['Herbaceous', 'Light', 'Savory'],
    spiceLevel: 1,
    prepTime: '25 min',
    priceXOF: 2100,
    priceUSD: 3.4,
    priceEUR: 3.0,
    drinkPairing: 'Fresh water',
    image: '../images/sukuma-wiki-kenya.jpg',
    funFact: 'Sukuma Wiki literally means "push the week" in Swahili.'
  },
  {
    id: 49,
    name: 'Doro Wat',
    country: 'Ethiopia',
    origin: 'Ethiopian Cuisine',
    category: 'Stew',
    history: 'A spicy chicken stew, the cornerstone of many celebrations in Ethiopia.',
    description: 'Chicken simmered in a berbere and tomato sauce, served with injera.',
    ingredients: ['Chicken', 'Berbere', 'Tomato', 'Onion', 'Garlic', 'Boiled egg'],
    flavors: ['Spicy', 'Aromatic', 'Rich'],
    spiceLevel: 4,
    prepTime: '1 h 30 min',
    priceXOF: 3900,
    priceUSD: 6.1,
    priceEUR: 5.3,
    drinkPairing: 'Ethiopian coffee',
    image: '../images/doro-wat-ethiopie.jpg',
    funFact: 'Doro wat is often served during religious holidays and weddings.'
  },
  {
    id: 50,
    name: 'Injera',
    country: 'Ethiopia',
    origin: 'Traditional Bread',
    category: 'Side dish',
    history: 'A fermented flatbread used as an edible plate to scoop up various dishes.',
    description: 'A light pancake with a tangy taste, the base of almost all Ethiopian meals.',
    ingredients: ['Teff', 'Water', 'Salt'],
    flavors: ['Slightly sour', 'Slightly sweet'],
    spiceLevel: 1,
    prepTime: '1 h 20 min',
    priceXOF: 1600,
    priceUSD: 2.5,
    priceEUR: 2.2,
    drinkPairing: 'Ethiopian coffee',
    image: '../images/injera-ethiopie.jpg',
    funFact: 'Injera also serves as a utensil; one uses it to grasp the food.'
  },
  {
    id: 51,
    name: 'Kitfo',
    country: 'Ethiopia',
    origin: 'Gurage Region',
    category: 'Meat',
    history: 'A dish of raw or lightly cooked beef, mixed with spiced butter and chili.',
    description: 'Minced beef seasoned with mitmita, served with injera and cottage cheese.',
    ingredients: ['Beef', 'Butter', 'Mitmita', 'Garlic', 'Salt', 'Cottage cheese'],
    flavors: ['Spicy', 'Buttery', 'Umami'],
    spiceLevel: 4,
    prepTime: '30 min',
    priceXOF: 4200,
    priceUSD: 6.6,
    priceEUR: 5.8,
    drinkPairing: 'Black tea',
    image: '../images/kitfo-ethiope.jpg',
    funFact: 'Kitfo is often prepared for major festive occasions in Ethiopia.'
  },
  {
    id: 52,
    name: 'Misir Wat',
    country: 'Ethiopia',
    origin: 'Vegetarian Cuisine',
    category: 'Soup',
    history: 'A highly appreciated red lentil stew in Ethiopian cuisine.',
    description: 'Red lentils simmered with berbere, onion, and garlic, served with injera.',
    ingredients: ['Red lentils', 'Berbere', 'Onion', 'Garlic', 'Tomato'],
    flavors: ['Spicy', 'Tomatoey', 'Aromatic'],
    spiceLevel: 3,
    prepTime: '45 min',
    priceXOF: 2600,
    priceUSD: 4.3,
    priceEUR: 3.8,
    drinkPairing: 'Ethiopian coffee',
    image: '../images/misir-wat-ethiopie.jpg',
    funFact: 'Misir wat is commonly prepared on fasting days (Mondays and Fridays) for Orthodox Christians.'
  },
  {
    id: 53,
    name: 'Shiro Wat',
    country: 'Ethiopia',
    origin: 'Family Cuisine',
    category: 'Sauce',
    history: 'A sauce made from chickpea or lentil flour, very nourishing.',
    description: 'A creamy legume sauce, often served with injera and vegetables.',
    ingredients: ['Chickpea flour', 'Onion', 'Garlic', 'Berbere', 'Oil'],
    flavors: ['Creamy', 'Spicy', 'Lightly spiced'],
    spiceLevel: 3,
    prepTime: '35 min',
    priceXOF: 2400,
    priceUSD: 4.0,
    priceEUR: 3.5,
    drinkPairing: 'Mint tea',
    image: '../images/shiro-wat-ethiopie.jpg',
    funFact: 'Shiro wat is a staple dish during vegetarian Orthodox fasting periods.'
  },
  {
    id: 54,
    name: 'Tibs',
    country: 'Ethiopia',
    origin: 'Northern Region',
    category: 'Grill',
    history: 'A sautéed meat dish often prepared for guests and special events.',
    description: 'Pieces of meat sautéed with onions and spices, served with injera.',
    ingredients: ['Meat', 'Onion', 'Bell pepper', 'Berbere', 'Garlic', 'Butter'],
    flavors: ['Smoked', 'Spicy', 'Aromatic'],
    spiceLevel: 3,
    prepTime: '40 min',
    priceXOF: 3800,
    priceUSD: 6.0,
    priceEUR: 5.2,
    drinkPairing: 'Ethiopian coffee',
    image: '../images/Tibs-ethiopie.jpg',
    funFact: 'Tibs is often prepared to celebrate the arrival of a special guest.'
  },
  {
    id: 55,
    name: 'Bobotie',
    country: 'South Africa',
    origin: 'Cape Malay Cuisine',
    category: 'Bake',
    history: 'A baked dish made with sweet-and-savory minced meat, very popular in South Africa.',
    description: 'Fragrant minced meat topped with a layer of egg and milk custard, baked until golden.',
    ingredients: ['Minced meat', 'Onion', 'Curry', 'Raisins', 'Milk', 'Egg'],
    flavors: ['Sweet', 'Mildly spicy', 'Creamy'],
    spiceLevel: 2,
    prepTime: '1 h',
    priceXOF: 3600,
    priceUSD: 5.7,
    priceEUR: 5.0,
    drinkPairing: 'Black tea',
    image: '../images/bobotie-sud-afrique.jpg',
    funFact: 'Bobotie is considered one of the national dishes of South Africa.'
  },
  {
    id: 56,
    name: 'Braai Boerewors',
    country: 'South Africa',
    origin: 'Afrikaner Cuisine',
    category: 'Grill',
    history: 'Sausage grilled during braais (barbecues), a symbol of South African conviviality.',
    description: 'Grilled beef and pork sausage, served with salad and bread.',
    ingredients: ['Beef', 'Pork', 'Garlic', 'Coriander', 'Paprika', 'Vinegar'],
    flavors: ['Smoked', 'Mildly spicy', 'Salty'],
    spiceLevel: 2,
    prepTime: '40 min',
    priceXOF: 3300,
    priceUSD: 5.2,
    priceEUR: 4.6,
    drinkPairing: 'Craft beer',
    image: '../images/braai-boerewors-sud-afrique.jpg',
    funFact: 'The "braai" is a social institution in South Africa, similar to a barbecue.'
  },
  {
    id: 57,
    name: 'Chakalaka and Pap',
    country: 'South Africa',
    origin: 'Township Cuisine',
    category: 'Side dish',
    history: 'A popular township dish, a mix of spicy vegetables and cornmeal porridge.',
    description: 'A spicy vegetable relish served with pap, a creamy cornmeal semolina.',
    ingredients: ['Cabbage', 'Tomato', 'Onion', 'Chili', 'Cornmeal', 'Butter'],
    flavors: ['Spicy', 'Sour', 'Mild'],
    spiceLevel: 3,
    prepTime: '35 min',
    priceXOF: 2500,
    priceUSD: 4.1,
    priceEUR: 3.6,
    drinkPairing: 'Lemon soda',
    image: '../images/chakalaka-et-pap-sud-afrique.jpg',
    funFact: 'Chakalaka is almost always served with pap during family meals.'
  },
  {
    id: 58,
    name: 'Potjiekos',
    country: 'South Africa',
    origin: 'Braai Cuisine',
    category: 'Stew',
    history: 'A slow-cooked stew prepared in a cast-iron pot, traditional among farmers.',
    description: 'Meat and vegetables simmered slowly in a pot over an open wood fire.',
    ingredients: ['Meat', 'Potato', 'Carrot', 'Onion', 'Vegetables', 'Spices'],
    flavors: ['Rich', 'Aromatic', 'Earthy'],
    spiceLevel: 2,
    prepTime: '2 h',
    priceXOF: 4100,
    priceUSD: 6.6,
    priceEUR: 5.8,
    drinkPairing: 'Black tea',
    image: '../images/potjiekos-sud-afrique.jpg',
    funFact: 'Potjiekos literally means "small pot food" in Afrikaans.'
  },
  {
    id: 59,
    name: 'Biltong',
    country: 'South Africa',
    origin: 'Snacks',
    category: 'Snack',
    history: 'Dried and salted meat, an excellent source of protein for travelers.',
    description: 'Thin slices of dried meat, spiced and slightly tangy.',
    ingredients: ['Beef', 'Salt', 'Pepper', 'Vinegar', 'Coriander', 'Paprika'],
    flavors: ['Salty', 'Smoked', 'Mildly spicy'],
    spiceLevel: 2,
    prepTime: '24 h',
    priceXOF: 2200,
    priceUSD: 3.8,
    priceEUR: 3.5,
    drinkPairing: 'Beer',
    image: '../images/biltong-sud-afrique.jpg',
    funFact: 'Biltong is a traditional snack that has been made for hundreds of years.'
  },
  {
    id: 60,
    name: 'Bunny Chow',
    country: 'South Africa',
    origin: 'Durban Cuisine',
    category: 'Street food',
    history: 'Hollowed-out bread filled with curry, originating in the Indian quarters of Durban.',
    description: 'Soft bread filled with a spicy meat or vegetable curry.',
    ingredients: ['Bread', 'Meat', 'Rice', 'Curry', 'Onion', 'Garlic'],
    flavors: ['Spicy', 'Curry', 'Savory'],
    spiceLevel: 4,
    prepTime: '50 min',
    priceXOF: 3000,
    priceUSD: 5.0,
    priceEUR: 4.4,
    drinkPairing: 'Chai tea',
    image: '../images/3. bunny-chow-sud-afrique.jpg',
    funFact: 'Bunny Chow was a portable meal for Indian workers in the early 20th century.'
  }
];
